<?php

namespace OrderBundle\Repository;

/**
 * OrderRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
