<?php

namespace OrderBundle\Repository;

/**
 * SpecialistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialistRepository extends \Doctrine\ORM\EntityRepository
{
}
